name: online_counsellor
description: Online Counselling section
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  flutter_smart_dialog: ^4.9.7+7
  google_fonts: ^6.2.1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  badges: ^3.1.2
  record: ^4.4.4
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  just_audio: ^0.9.38
  simple_ripple_animation: ^0.0.9
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/images/
# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image_dark: assets/logo/logo.png
  icon_background_color_dark: "#ffffff"
  image: assets/logo/logo.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/logo/logo_android_12.png
    icon_background_color: "#ffffff"
    image_dark: assets/logo/logo_android_12.png
    icon_background_color_dark: "#ffffff"
#dart run flutter_native_splash:create